- name: Hello world
  hosts: local
  connection: local
  tasks:
    - name: Print Hello world
      ansible.builtin.debug:
          msg: "Hello world"

- name: Play-2
  hosts: local
  connection: local
  tasks:
    - name: Task from play 2
      ansible.builtin.debug:
        msg: " Hi i am form play 2"