- name: Installing the Ngnix
  hosts: local
  connection: local
  become: yes
  tasks:
    - name: Installing the nginx
      ansible.builtin.package:
        name: nginx
        state: present
    - name: Start nginx
      ansible.builtin.service:
        name: nginx
        state: started
      