- name: Task level variables
  hosts: local
  connection: local
  vars:
    Course: "Jagadeesh"
    Experience: "2 years"
  tasks:
  - name: print variables
    vars:
     Experience: "4 years"
    ansible.builtin.debug:
      msg: "Hi i am {{Course}} i have {{Experience}}"
